 name: Untrust BoM
 on:
  workflow_dispatch:
 
 
 jobs:
  untrust:
     runs-on: ubuntu-latest
     steps:
         - uses: actions/checkout@v2
           name: Checkout code
           
         - uses: codenotary/vcn-untrust-bom-python-github-action@v1.0.0
          # uses: codenotary/vcn-untrust-bom-python-github-action@main
           with:
             asset: git://.
             cnil_host: ${{ secrets.CNIL_HOST }}
             cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
             cnil_api_key: ${{ secrets.CNIL_API_KEY }}
